version: "3.9"

services:
  app:
    image: app
    container_name: ${DOCKER_APP_NAME:-project}-app
    volumes:
        - ./storage:/app/storage:cached
    build:
        args:
            port: ${APP_SERVER_PORT:-8080}
        context: ./
        dockerfile: Dockerfile
    ports:
        - "${DOCKER_APP_PORT:-8080}:${APP_SERVER_PORT:-8080}"